# Generated by Django 4.2.3 on 2023-07-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantitity',
            field=models.IntegerField(default=1),
        ),
    ]
